### ISSUE TITLE
Docs refer to wrong version of embedded_hal

### ISSUE THREAD

**Issue by elpiel** [embassy-rs/docserver#2]
The `Adc` struct of `embassy_rp` implements `Channel` from `embedded_hal 0.2` but the URL in the docs points to `1.0.0-alpha.9` and once clicked it shows 404.

https://docs.embassy.dev/embassy-rp/git/rp2040/adc/struct.Adc.html#implementations

**Comment by peter-lyons-kehl** [comment]
This comes from `embassy/embassy-rp` > `Cargo.toml`:
```toml
embedded-hal-02 = { package = "embedded-hal", version = "0.2.6", features = ["unproven"] }
embedded-hal-1 = { package = "embedded-hal", version = "=1.0.0-alpha.9", optional = true}
```
There is https://docs.rs/embedded-hal/0.2.6/embedded_hal/adc/trait.Channel.html, but no counterpart under https://docs.rs/embedded-hal/1.0.0-alpha.9/embedded_hal/index.html.

Any tips, please?
